version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3

jobs:
  setup_circleci-machine:
        machine:
          image: ubuntu-2204:current
        steps:
          - run: echo "Continuous Integration Rocks!"
          - run: echo "completed"
workflows:
  all_jobs:
    jobs:
    - setup_circleci-machine