version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3

jobs:
  setup_circleci-machine:
        machine:
          image: ubuntu-2204:current
        steps:
          - run: sudo apt-get update && sudo apt-get install -y cowsay
          - run: cowsay Continuous Integration Rocks!
workflows:
  all_jobs:
    jobs:
    - setup_circleci-machine