version: 2.1

jobs:
  build:
    docker: 
      - image: cimg/base:current
    steps:
      - checkout 
      - run: echo "Terraform Job is about to start"
workflows:
    demo-workflows:
      jobs:
        - build