version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
# Jobs to Run
commands:
  stage-initializations:
    steps: 
      - run:
          command: |
            echo "Continuous Integration Rocks!"
            echo "completed"
jobs:
  setup_circleci-machine:   # Job Name
    machine:                # Executor type
     image: ubuntu-2204:current
  # Steps for the jobs
    steps:
      - run: 
         name: show run_command
         command: stage-initializations

  install_terraform:
    docker:
      - image: hashicorp/terraform:latest
    resource_class: medium
    steps:
      - checkout
      - run:
          name: install terraform
          command: |
            terraform init 
            terraform fmt 
      - run:
          name: list bucket
          command: aws s3 ls
workflows:
  all_jobs:
    jobs:
    - setup_circleci-machine
    - install_terraform