version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.1.1
  aws-cli: circleci/aws-cli@4.1.3

parameters:
  run_prod_job:
    type: boolean
    default: false

  changeset:
    type: string
    default: ""

  commit_id:
    type: string
    default: ""

  plan:
    type: string
    default: ""

executors:
  ubuntu:
    machine:
      image: ubuntu-2204:current

jobs:
  show_changeset:
    executor: ubuntu
    resource_class: medium
    steps:
      - run: 
          name: show changeset and plan
          command: |
            echo "Changes to be deployed: "
            echo << pipeline.parameters.changeset >>
            echo "Plan to be deployed: "
            echo << pipeline.parameters.commit_id >>
  build:
    executor: ubuntu
    resource_class: medium
    steps:
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
  start_prod_job:
    executor: ubuntu
    resource_class: medium
    environment:
      CHANGESET: << pipeline.parameters.changeset >>
      COMMIT_ID: << pipeline.parameters.commit_id >>
    steps:
      # - aws-cli/setup
      - run:
          name: Assume Sec role and start codebuild
          command: | 
            echo "Starting PRO codebuild with changeset: "
            echo << pipeline.parameters.changeset >>
            echo "Commit ID is ${COMMIT_ID}"
            echo "Assume Sec Role"
  deploy:
    executor: ubuntu
    resource_class: medium
    steps:
      - checkout          
      - run: 
          name: deploy to s3
          command: aws s3api create-bucket --bucket bucketformpipeline --region us-east-1


workflows:
  codepipeline:
    # when: << pipeline.parameters.run_prod_job >>
    jobs:
      - show_changeset
      - start_prod_job
      - build
      - deploy:
          requires:
          - build
          filters:
            branches:
              only: main